version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgre
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    ports:
      - 5432:5432
